# project settings for Makefile

# spell-checker:ignore (C/C++ Makefile) CPPFLAGS ; (libs) shlwapi

CPPFLAGS_cl := /std:c++17
CPPFLAGS_clang := -std=c++17
CPPFLAGS_gcc := ${CPPFLAGS_clang}

LIBS := shell32 shlwapi $()## list of any additional required libraries (space-separated); alternatively, use `#pragma comment(lib, "LIBRARY_NAME")` (but NOTE: pragma not supported by `gcc`; ref:<https://stackoverflow.com/questions/1685206>)
