name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYS2_PATH_TYPE: inherit
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build
        run: make
