name: Release

on:
  schedule:
    - cron: '0 0 * * 0' # weekly
  workflow_dispatch:
  push:
    tags:
      - 'v**'

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYS2_PATH_TYPE: inherit
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: false
          release: false
          install: >-
            zip
            ninja
      - uses: actions/checkout@v2
      - name: Get latest release
        continue-on-error: true
        id: cur_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: draft

      - name: Get version
        run: |
          tag=${GITHUB_REF#refs/tags/*}
          sha=${GITHUB_SHA::7}
          version=$([[ $tag == v* ]] && echo ${tag:1} || echo 3.0.$sha)
          cur_ver=$([[ ${{ steps.cur_release.outcome }} == failure ]] && echo v0 || echo ${{ steps.cur_release.outputs.release }})
          [[ v$version == $cur_ver ]] && exit 1
          prerelease=$([[ $tag == v* ]] && echo false || echo true)
          echo "version=$version" >> $GITHUB_ENV
          echo "prerelease=$prerelease" >> $GITHUB_ENV

      - name: Build
        run: make

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.version }}
          name: ${{ env.version }}
          draft: false
          prerelease: ${{ env.prerelease }}
          artifactErrorsFailBuild: true
          artifacts: \#build/shimexe.zip
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}
